[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PryfynMeth"
version = "1.0.0"
description = "Tools for Preprocessing Invertebrate Methylation Data"
authors = [
    { name = "C L Thomas", email = "Christianluthomas@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
dependencies = [
    "pandas",
    "numpy"
]

[tool.setuptools.packages.find]
where = ["."]
